### Alle Moods abrufen (GET)
GET https://feelique-back.onrender.com/moods

### Neuen Mood erstellen (POST)
POST https://feelique-back.onrender.com/moods
Content-Type: application/json

{
  "mood": "Glücklich",
  "time": "2025-12-17T21:00:00"
}

### Einen bestimmten Mood abrufen (GET by ID)
GET https://feelique-back.onrender.com/moods/1

### Einen bestimmten Mood löschen (DELETE by ID)
DELETE https://feelique-back.onrender.com/moods/9









### Alle Moods abrufen (GET)
GET http://localhost:8080/moods
X-Session-Token: ed7d307c-21b9-45e0-a510-fb58796b1305

### Neuen Mood erstellen (POST)
POST http://localhost:8080/moods
X-Session-Token: 5d97aed7-10cb-42f6-8351-935692b183b1
Content-Type: application/json

{
  "mood": "Glücklich",
  "note": "Test",
  "time": "2025-12-17T21:00:00"
}

### Einen bestimmten Mood abrufen (GET by ID)
GET http://localhost:8080/moods

### Einen bestimmten Mood löschen (DELETE by ID)
DELETE http://localhost:8080/moods/2


### Eine Emailadresse erstellen (POST)
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "123456"
}

### Mit Email Anmelden (POST)
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "yasmin.yelgin@student.htw-berlin.de",
  "password": "M1laUni-2024"
}